baseURL = ""
# "https://joannalei21.github.io/"
languageCode = 'en'
title = "Joanna's Blog"
theme = "dream"
hasCJKLanguage = true

# [services]
# [services.disqus]
# shortname = ""
# [services.googleAnalytics]
# ID = ""

[params]
# zenMode = true
lightTheme = "emerald"
darkTheme = "forest"

backgroundImage = "/background.png"
# backgroundImageDark = ""

author = "Joanna Lei"
# description = "èµ°åœ¨æˆç‚ºå·¥ç¨‹å¸«çš„è·¯ä¸Š"
avatar = "cat.png"
headerTitle = "Joanna's Bolg"
# motto = ""


footerBottomText = "ğŸŒŸ A Hugo theme named Dream"

# rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

# email = ""

siteStartYear = 2024

favicon = "favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
# stickyNav = true
# reorderNavItems = ["search", "rss", "posts", "categories", "tags"]
# collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
showPrevNextPost = true
# reorderShares = ["x", "facebook", "whatsapp"]




# [params.navItems]

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

# [params.experimental]
# jsDate = true
# jsDateFormat = "yyyyå¹´MMæœˆddæ—¥"